[package]
name = "git-revision"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Commit walking and revision listing"

[dependencies]
git-hash = { path = "../git-hash" }
git-object = { path = "../git-object" }
git-core = { path = "../git-core" }
git-odb = { path = "../git-odb" }
git-refs = { path = "../git-refs" }
